version: '3.1'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secreta
      POSTGRES_DB: 3itencuenta
    container_name: 3itencuenta
    volumes:
      - ./postgresql:/var/lib/postgresql/data